spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academy
    username: root
    password: zlqhem55k
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true