spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academy
    username: root
    password: zlqhem55k
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# JWT 설정 추가
jwt:
  secretKey: TXlTdXBlclNlY3JldEtleQ==   # 원하는 시크릿 키 입력(MySuperSecretKey를 Encode)
  expiration: 300                       # 만료 시간(5분)