spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsfeed?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: {YOUR_DB_USER}
    password: {YOUR_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # ?? ??? ?? ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    time-zone: Asia/Seoul


server:
  port: 8080


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace