### 회원가입
# @name signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "0000aaAA1!",
  "userName": "애플1"
}

### 로그인(JWT 발급)
# @name login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "0000aaAA!"
}

### logout
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwianRpIjoiMDgyOTY2NzEtM2U0ZS00NGM5LTkxYWMtNWQ1OWYyOTA3NWJhIiwidXNlcklkIjoxLCJleHAiOjE3NTU3NjYwNDF9.7rm1OXpb0YXCGWZy3MagCtw8Q0TUYz8uOtu_lfo3Xds


/// 여기까지 확인 완료